### ISSUE TITLE
原生js 如何引入？

### ISSUE THREAD

**Issue by yichengxian** [zhengxs2018/calendar-data#1]
如题

**Comment by zhengxs2018** [comment]
你说的是直接在创建的 HTML 中使用？

1、使用 CDN: 比如 unpkg, jsDelivr 等

- [UNPKG](https://www.unpkg.com)
- [jsDelivr](https://www.jsdelivr.com/)

示例链接

```sh
# unpkg
https://www.unpkg.com/@zhengxs/calendar-data/dist/calendar-data.umd.js

# jsDelivr
https://cdn.jsdelivr.net/npm/@zhengxs/calendar-data/dist/calendar-data.umd.js
```

2、直接下载 dist 中 umd 文件

<img width="896" alt="image" src="https://github.com/zhengxs2018/calendar-data/assets/7506913/618c386d-e5ef-4d7c-b3b7-bdeb68fddfd7">

传送门：[npm: @zhengxs/calendar-data](https://www.npmjs.com/package/@zhengxs/calendar-data?activeTab=code)

**Comment by zhengxs2018** [comment]
如果你只是简单的想要生成日期数据，我推荐你看下我写的那篇文章，其实代码并没有多少。

[面向初学者：如何写一个日历组件](https://juejin.cn/post/6910585443345235975)
