### ISSUE TITLE
哈哈哈, 你的掘金博客可以看到

### ISSUE THREAD

**Issue by zhenfang0215** [zhengxs2018/calendar-data#2]
我发现掘金上面你已经注销账号了,但是实际上从搜索引擎还能搜索到你的博客, 我感觉这应该不符合你的预期吧,和你说一声hhh. https://juejin.cn/post/6910585443345235975

<img width="1356" alt="image" src="https://github.com/zhengxs2018/calendar-data/assets/104150263/e14a65f2-c9fb-4948-ac51-d4fcd8b0e5ec">

**Comment by zhengxs2018** [comment]
感谢！

其实并不是，我删账号是因为情绪比较低落，加上当时的掘金氛围不好，不想要玩了。

至于文章写出来就是给人看的，毕竟也是我的成果，如果能帮到你，那对我来说也是件高兴的事情。

而且我仓库的 Readme 还挂着那个链接，哈哈哈哈。
